### PR TITLE
Update non_es_en_template.yml

### PR DESCRIPTION
**Pull request by Darrell-c**
Kazakh translations for dos_emb_csa_kazakhstan_kazakh

Thanks

### CODE REVIEW

**Comment by noremmie** [comment]
Thanks for this, @Darrell-c! Before I merge this, can you do me a favor and make a couple modifications in your `Darrell-c:patch-3` branch please?

* move the current contents of `localizations/non_es_en_template.yml` into a new file: `localizations/kk.yml`
* restore the original contents of `localizations/non_es_en_template.yml`

When that's done the PR should be proposing no changes to `localizations/non_es_en_template.yml`, and it should be only introducing a new file: `localizations/kk.yml`.

Please see [this commit](https://github.com/GSA/punchcard/commit/2ffc20fa32911a3a701bd7186248961f30b10ed2) which introduces a single new `lo.yml` file as an example.

**Comment by Darrell-c** [comment]
OK ... I think I got it. At least I think so ☺

https://github.com/Darrell-c/punchcard/blob/patch-4/localizations/kk.yml



*Darrell Cochran*PMP
IIP Office of Digital Publishing

**Comment by noremmie** [comment]
Thanks, @Darrell-c - I'll create a PR with your `patch-4` branch and usher it through the process. I think I need to patch one thing up with a commit that I'll squash into yours when merging the PR.

Thanks again.

**Comment by Darrell-c** [comment]
Thans!


*Darrell Cochran*PMP
IIP Office of Digital Publishing

**Comment by noremmie** [comment]
These new localizations are live now on the DigitalGov Search site. Thanks, @Darrell-c.

https://search.usa.gov/search?affiliate=dos_emb_csa_kazakhstan_kazakh

**Pull request closed without merging**
