### PR TITLE
add gov jargon: eRegulations

### PR DESCRIPTION
**Pull request by dawnpm**

### CODE REVIEW

**Comment by jamesisaacs** [comment]
We have the same stemmer issue here with the `:analyzed:` field as in https://github.com/GSA/punchcard/pull/30. The `:analyzed:` entry would be `reg`, `regul`, `eregul` and `ereg`. Otherwise, this LGTM.

**Comment by dawnpm** [comment]
Thanks. Am super excited for the punchcard integration to get going. Progress!

**Comment by dawnpm** [comment]
All clear now?

**Comment by jamesisaacs** [comment]
yep. Ready to squash and merge.

**Pull request merged**
