### PR TITLE
Add "id" and "apply"

### PR DESCRIPTION
**Pull request by dawnpm**
I don't know if I did the `:analyzed:` line correctly, but do we even need this any more?

### CODE REVIEW

**Comment by jamesisaacs** [comment]
The `:analyzed:` field looks only informational. Since we changed the stemmer for English, most if not all of the synonym entries need to be updated. The stemmed versions (using the Porter stemmer) of `id`, `identification`, `identity`, `identify` for the `:analyzed:` field would be `id`, `identif`, `ident`, and `identifi`. Otherwise, this LGTM.

**Comment by jamesisaacs** [comment]
@dawnpm you're missing an `identifi` at the end of `:analyzed:`

**Comment by dawnpm** [comment]
`identifi` for "identification" or "identify"? those don't both stem down to `identif`?

**Comment by jamesisaacs** [comment]
nope. `identification` stems to `identif` and `identify` to `identifi` using Porter.

**Comment by dawnpm** [comment]
hm!

**Pull request merged**
