### PR TITLE
Add Lao localizations provided by Darrell-c

### PR DESCRIPTION
**Pull request by noremmie**
@Darrell-c thanks for providing these Lao localizations! I've moved the localizations you provided into their own `lo.yml` file, but there are a couple missing. I left them as "FIXME". Would you mind providing Lao localizations for the following strings please?

* videos
* default_rss_govbox_label

Please feel free to leave them as comments here or to add a new commit that edits out my "FIXME"s. Once that's done, I can take care of shepherding these new localizations into usasearch production.

### CODE REVIEW

**Comment by Darrell-c** [comment]
Nate - Laos doesn't use the Video or Default_RSS in their search. I've removed them from the master.

/Darrell

**Comment by Darrell-c** [comment]
Oops - I couldn't remove them, but we should go ahead and delete them from the file.

/d

**Comment by Darrell-c** [comment]
Thanks Nate, see my comments.

/Darrell


*Darrell Cochran*PMP
IIP Office of Digital Publishing

**Comment by dawnpm** [comment]
@Darrell-c - if they're not used, we can just leave them blank. In the off chance that those features get turned on at some point, they would default to an English label. Sound good?

**Comment by Darrell-c** [comment]
Perfect.



*Darrell Cochran*PMP
IIP Office of Digital Publishing

**Comment by noremmie** [comment]
OK, I just tested the punchcard/usasearch integration for this in a demo environment, and everything checks out. Thanks again for the localizations @Darrell-c.

**Pull request merged**
